export const ALERT = {
  UPDATE: "ALERT__UPDATE",
  REMOVE: "ALERT__REMOVE",
}

export const TURN = {
  SET_PLAYER_QUEUE: "TURN__SET_PLAYER_QUEUE",
  INCREMENT: "TURN__INCREMENT",
  END_GAME: "TURN__END_GAME"
}

export const SCORE = {
  INIT: "SCORE__INIT",
  PUSH: "SCORE__PUSH",
  SUBMIT_FINAL_SCORE: "SCORE__SUBMIT_FINAL_SCORE",
}