export const ALERT = {
  UPDATE: "ALERT__UPDATE",
  REMOVE: "ALERT__REMOVE",
}

export const TURN = {
  SET_PLAYER_QUEUE: "TURN__SET_PLAYER_QUEUE",
  INCREMENT: "TURN__INCREMENT",
  ADD_EXTRA_TURN: "TURN__ADD_EXTRA_TURN",
}

export const SCORE = {
  INIT: "SCORE__INIT",
  PUSH: "SCORE__PUSH",
}